# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
$:.unshift File.expand_path("../../lib", __FILE__)

def jruby?
  defined?(RUBY_ENGINE) && RUBY_ENGINE == 'jruby'
end

def macruby?
  defined?(RUBY_ENGINE) && RUBY_ENGINE == 'macruby'
end

unless ENV["CI"] || macruby?
  require 'simplecov'
  SimpleCov.start 'test_frameworks'
end

require 'dotify'
require 'ostruct'
Dir["./spec/support/**/*.rb"].each { |f| require f }

RSpec.configure do |c|
  c.treat_symbols_as_metadata_keys_with_true_values = true
  c.run_all_when_everything_filtered = true
  c.filter_run :focus

  c.before(:each) do
    Thor::Util.stub(:user_home) { '/tmp/home' }
  end
end
